
# The name of your website.
name: zen habits

description:
  # Description of your site. This will show up in google.
  meta:
  # Description of your site. This will show up on the front page.
  subtitle:

author:
  name: Valentin Umbach
  # Necessary for contact page
  email:
  # Optional text (html) to display after author name. Leave empty if you don't
  # want it.
  info:

url: http://zen-habits.github.io
baseurl: ""

# language attribute in <html> element.
lang: de

# FROM THIS POINT ON EVERYTHING IS OPTIONAL

##############
# APPEREANCE #
##############

# If you want to show the subtitle anywhere else than the front page, use
# {% include subtitle.html %} to include it anywhere you want.
show-subtitle: false
display-social-icons: false

footer-text:

# Preferably 64px in height. Leave empty = disable.
logo-image:

# Toolbar color for Chrome on Android.
theme-color-attr: "#00f0ff"

# Color of Microsoft live Tile.
ms-tile-color: "#00f0ff"

# Color used throughout the theme. Format: R, G, B.
theme-color: 0, 240, 255 # Original: 0, 240, 255

# Text color used throughout the theme. Format: R, G, B.
text-color: 0, 0, 0 # Original: 0, 0, 0

# Background color used throughout the theme. Format: R, G, B.
# Note: if you change the background color AND you use cover images, you should
#       also change the CSS gradient in "_includes\gradient.css" to match the
#       background color. Edit and copy it from here:
#       http://www.colorzilla.com/gradient-editor/#ffffff+0,ffffff+100&0+0,1+100
background-color: 255, 255, 255 # Original: 255, 255, 255

display-author-post-page: true
display-author-front-page: true

# http://alanwsmith.com/jekyll-liquid-date-formatting-examples
date_format: "%-d %b %Y"

# Minimal screen-width after which the navigation will change position from
# vertical to horizontal.
nav-breaking-point: 520px

# Display links for the previous and next post on post pages.
display-next-prev-post: false


#####################
# CUSTOMIZABLE TEXT #
#####################

# Useful for translating into other languages.

var_on_the_web: On the web
var_read: Read # Text after each post summary on the homepage.
var_newer: Newer
var_older: Older
var_next_post: Next post
var_previous_post: Previous post
var_less_than_a_minute_read: Less than a minute read
var_min_read: Min zu lesen # Text after reading time. Example: 5 min read.
var_post_by: Post by
var_guest_post_by: Guest post by
var_your_email: Your email
var_your_message: Your message
var_original_by: Original von
var_translation_by: Ãœbersetzung von


##################
# BUILD SETTINGS #
##################

# You don't have to change these.

exclude: [vendor]
kramdown:
  input: GFM
permalink: "/:title"
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"